/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import AppPackage.AnimationClass;
import java.awt.Toolkit;
import javax.swing.JOptionPane;


/**
 *
 * @author Perdomo
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    AnimationClass cc = new AnimationClass();
    

    
    public Inicio() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage("src/imagenes/logoEventos Blanquel.jpg"));        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        presupuesto = new javax.swing.JButton();
        inventario = new javax.swing.JButton();
        eventos = new javax.swing.JButton();
        corte = new javax.swing.JButton();
        factura = new javax.swing.JButton();
        clientes = new javax.swing.JButton();
        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eventos Blanquel");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Menu_32px_1.png"))); // NOI18N
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        getContentPane().add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, -1, 30));

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Multiply_32px.png"))); // NOI18N
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        getContentPane().add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, -1, -1));

        presupuesto.setBackground(new java.awt.Color(119, 15, 50));
        presupuesto.setForeground(new java.awt.Color(255, 255, 255));
        presupuesto.setText("Presupuesto");
        presupuesto.setMargin(new java.awt.Insets(2, 20, 2, 20));
        presupuesto.setMaximumSize(new java.awt.Dimension(81, 23));
        presupuesto.setMinimumSize(new java.awt.Dimension(81, 23));
        presupuesto.setPreferredSize(new java.awt.Dimension(111, 23));
        presupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presupuestoActionPerformed(evt);
            }
        });
        getContentPane().add(presupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 70, 160, 30));

        inventario.setBackground(new java.awt.Color(119, 15, 50));
        inventario.setForeground(new java.awt.Color(255, 255, 255));
        inventario.setText("Inventario");
        inventario.setMargin(new java.awt.Insets(2, 20, 2, 20));
        inventario.setPreferredSize(new java.awt.Dimension(111, 23));
        inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioActionPerformed(evt);
            }
        });
        getContentPane().add(inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 120, 160, 30));

        eventos.setBackground(new java.awt.Color(119, 15, 50));
        eventos.setForeground(new java.awt.Color(255, 255, 255));
        eventos.setText("Eventos");
        eventos.setMargin(new java.awt.Insets(2, 20, 2, 20));
        eventos.setPreferredSize(new java.awt.Dimension(111, 23));
        eventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventosActionPerformed(evt);
            }
        });
        getContentPane().add(eventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 220, 160, 30));

        corte.setBackground(new java.awt.Color(119, 15, 50));
        corte.setForeground(new java.awt.Color(255, 255, 255));
        corte.setText("Corte de Ventas");
        corte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corteActionPerformed(evt);
            }
        });
        getContentPane().add(corte, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 170, 160, 30));

        factura.setBackground(new java.awt.Color(119, 15, 50));
        factura.setForeground(new java.awt.Color(255, 255, 255));
        factura.setText("Factura");
        factura.setMargin(new java.awt.Insets(2, 20, 2, 20));
        factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturaActionPerformed(evt);
            }
        });
        getContentPane().add(factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 320, 160, 30));

        clientes.setBackground(new java.awt.Color(119, 15, 50));
        clientes.setForeground(new java.awt.Color(255, 255, 255));
        clientes.setText("Clientes");
        clientes.setMargin(new java.awt.Insets(2, 20, 2, 20));
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });
        getContentPane().add(clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 270, 160, 30));

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoEventos Blanquel.jpg"))); // NOI18N
        jcMousePanel1.setIconLogo(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cero.png"))); // NOI18N

        javax.swing.GroupLayout jcMousePanel1Layout = new javax.swing.GroupLayout(jcMousePanel1);
        jcMousePanel1.setLayout(jcMousePanel1Layout);
        jcMousePanel1Layout.setHorizontalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        jcMousePanel1Layout.setVerticalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        getContentPane().add(jcMousePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 488, 470));

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setOpaque(true);
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void presupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presupuestoActionPerformed
       new Presupuesto1().setVisible(true);
        dispose();
    }//GEN-LAST:event_presupuestoActionPerformed

    private void inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioActionPerformed
        new Inventario().setVisible(true);
        dispose();
    }//GEN-LAST:event_inventarioActionPerformed

    private void eventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventosActionPerformed
        new Eventos().setVisible(true);
        dispose();
    }//GEN-LAST:event_eventosActionPerformed

    private void corteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corteActionPerformed
        new CorteVentas().setVisible(true);
        dispose();
    }//GEN-LAST:event_corteActionPerformed

    private void facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturaActionPerformed
        new Factura().setVisible(true);
        dispose();
    }//GEN-LAST:event_facturaActionPerformed

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        new Clientes().setVisible(true);
        dispose();
    }//GEN-LAST:event_clientesActionPerformed

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setState(Inicio.ICONIFIED);
    }//GEN-LAST:event_minimizarMouseClicked

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null,"Estas seguro de salir","Saliendo del Sistema",dialog);
        if(result==0)
        {
            dispose();
            
        }
    }//GEN-LAST:event_cerrarMouseClicked

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        cc.jButtonXRight(-160, 10, 10, 5, presupuesto);
        cc.jButtonXLeft(10, -160, 10, 5, presupuesto);
        cc.jButtonXRight(-160, 10, 10, 5, inventario);
        cc.jButtonXLeft(10, -160, 10, 5, inventario);
        cc.jButtonXRight(-160, 10, 10, 5, clientes);
        cc.jButtonXLeft(10, -160, 10, 5, clientes);
        cc.jButtonXRight(-160, 10, 10, 5, eventos);
        cc.jButtonXLeft(10, -160, 10, 5, eventos);
        cc.jButtonXRight(-160, 10, 10, 5, factura);
        cc.jButtonXLeft(10, -160, 10, 5, factura);
        cc.jButtonXRight(-160, 10, 10, 5, corte);
        cc.jButtonXLeft(10, -160, 10, 5, corte);
    }//GEN-LAST:event_menuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cerrar;
    private javax.swing.JButton clientes;
    private javax.swing.JButton corte;
    private javax.swing.JButton eventos;
    private javax.swing.JButton factura;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton inventario;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel minimizar;
    private javax.swing.JButton presupuesto;
    // End of variables declaration//GEN-END:variables
}
