/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Perdomo
 */
public class Presupuesto1 extends javax.swing.JFrame {

    /**
     * Creates new form Presupuesto1
     */
    public Presupuesto1() {
        initComponents();
        int id = 1;
        this.Folio.setText("No.  " + id);
        opciones.add(renta);
        opciones.add(servicio);
        opciones.add(evento);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opciones = new javax.swing.ButtonGroup();
        nomtext2 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        productos = new javax.swing.JTextArea();
        btnBuscador = new javax.swing.JButton();
        cantidadtext = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        nomtext1 = new javax.swing.JTextField();
        Folio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        servicio = new javax.swing.JRadioButton();
        evento = new javax.swing.JRadioButton();
        renta = new javax.swing.JRadioButton();
        fdevolucion = new com.toedter.calendar.JDateChooser();
        fentrega = new com.toedter.calendar.JDateChooser();
        fevento = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        buscatext = new javax.swing.JTextField();
        dirtext = new javax.swing.JTextField();
        ciutext = new javax.swing.JTextField();
        cptext = new javax.swing.JTextField();
        teltext = new javax.swing.JTextField();
        subtotal = new javax.swing.JTextField();
        desc = new javax.swing.JTextField();
        deposito = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Mensaje = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        regresar = new javax.swing.JButton();
        Generar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        nomtext3 = new javax.swing.JTextField();

        nomtext2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productos.setColumns(0);
        productos.setRows(5);
        jScrollPane5.setViewportView(productos);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 610, 100));

        btnBuscador.setText("Buscar");
        btnBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscadorActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 110, 30));

        cantidadtext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cantidadtext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidadtextKeyPressed(evt);
            }
        });
        getContentPane().add(cantidadtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 110, 30));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel18.setText("Buscar:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, 30));

        nomtext1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(nomtext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 250, 30));

        Folio.setEditable(false);
        Folio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Folio.setForeground(new java.awt.Color(255, 0, 0));
        Folio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FolioActionPerformed(evt);
            }
        });
        getContentPane().add(Folio, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 41, 80, 21));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Folio:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 50, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel6.setText("Telefono:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setText("Dirección:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel10.setText("Concepto:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel11.setText("Fecha de Evento:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setText("Ciudad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel12.setText("Codigo Postal:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, 30));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setText("Fecha de Entrega:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 30));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setText("Fecha de Devolución:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, 30));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel15.setText("Cantidad:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 30));

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Multiply_32px.png"))); // NOI18N
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        getContentPane().add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        getContentPane().add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, -1, -1));

        servicio.setBackground(new java.awt.Color(255, 255, 255));
        servicio.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        servicio.setText("Servicio");
        servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicioActionPerformed(evt);
            }
        });
        getContentPane().add(servicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 30));

        evento.setBackground(new java.awt.Color(255, 255, 255));
        evento.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        evento.setText("Evento");
        getContentPane().add(evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, 30));

        renta.setBackground(new java.awt.Color(255, 255, 255));
        renta.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        renta.setText("Renta");
        renta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentaActionPerformed(evt);
            }
        });
        getContentPane().add(renta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, 30));

        fdevolucion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(fdevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 130, 30));

        fentrega.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(fentrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 130, 30));

        fevento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(fevento, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 130, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Desc. $");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 60, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Total $");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, -1, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("CANTIDAD CON LETRA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, -1, 30));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel17.setText("Cliente:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 30));

        buscatext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buscatext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscatextKeyPressed(evt);
            }
        });
        getContentPane().add(buscatext, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 230, 30));

        dirtext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dirtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirtextActionPerformed(evt);
            }
        });
        getContentPane().add(dirtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 250, 30));

        ciutext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(ciutext, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 200, 30));

        cptext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(cptext, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 50, 30));

        teltext.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        teltext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teltextActionPerformed(evt);
            }
        });
        getContentPane().add(teltext, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 90, 30));

        subtotal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 130, 30));

        desc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descActionPerformed(evt);
            }
        });
        getContentPane().add(desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 130, 30));

        deposito.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(deposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 330, 30));

        total.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, 130, 30));

        Mensaje.setColumns(20);
        Mensaje.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Mensaje.setRows(5);
        Mensaje.setText("Observaciones: Debido al tipo de mobiliario, loza, manteleria, \nequipo y utensilios es necesario recibir en garantía, un depósito \nen efectivo, que sufrague parte del valor económico del mobiliario\n el cual será reembolsado a la entrega del mobiliario proporcionado\n y en caso de tener algún daño, este será pagado en su totalidad al \n100% ");
        jScrollPane2.setViewportView(Mensaje);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 400, 110));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(180);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 610, 100));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("Depósito $");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, -1, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Subtotal $");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, -1, 30));

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 680, -1, 30));

        Generar.setText("Generar");
        Generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarActionPerformed(evt);
            }
        });
        getContentPane().add(Generar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 680, -1, 30));

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setOpaque(true);
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 630, 790));

        nomtext3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(nomtext3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 250, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Estas seguro de salir", "Saliendo del Sistema", dialog);
        if (result == 0) {
            dispose();
            
        }
    }//GEN-LAST:event_cerrarMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setState(Inicio.ICONIFIED);
    }//GEN-LAST:event_minimizarMouseClicked

    private void FolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FolioActionPerformed

    }//GEN-LAST:event_FolioActionPerformed

    private void dirtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dirtextActionPerformed

    private void teltextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teltextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teltextActionPerformed

    private void servicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_servicioActionPerformed

    private void rentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentaActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        new Inicio().setVisible(true);
        dispose();
    }//GEN-LAST:event_regresarActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descActionPerformed

    private void GenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarActionPerformed
        String fecha = " ";
        System.out.println("" + this.fevento.getDateFormatString());
        System.out.println("tu fecha es: " + fecha);

    }//GEN-LAST:event_GenerarActionPerformed

    private void buscatextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscatextKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscatextKeyPressed
    static int idMob;
    static String descrip;
    static float precio;
    static int p_unitario;
    static int nexistencia;
    static String provedor;
    static int con = 0;
    private void btnBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscadorActionPerformed
        
        try {
            String descripcion = buscatext.getText();
            System.out.println(descripcion);
            //SELECT idMob FROM Mobiliario WHERE descrip=descripcion;

            Connection conexion;
            
            Class.forName("com.mysql.jdbc.Driver");
            conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/pruebas?zeroDateTimeBehavior=convertToNull", "root", "");
            PreparedStatement consulta;
            consulta = conexion.prepareStatement("SELECT * FROM Mobiliario WHERE descrip='" + descripcion + "'");
            System.out.println(consulta);
            ResultSet resultado = consulta.executeQuery();
            
            while (resultado.next()) {
                descrip = resultado.getString("descrip");
                p_unitario = resultado.getInt("p_unitario");
                nexistencia = resultado.getInt("nexistencia");
                provedor = resultado.getString("provedor");
                System.out.println(idMob + "  /   " + descrip + "  / " + precio + "   /   " + p_unitario + "  /   " + nexistencia + " /   " + provedor);
            }
            float importe = p_unitario * Integer.parseInt(cantidadtext.getText());
            list.add(descrip);
            list.add(p_unitario);
            list.add(importe);
            datos.add(list);
            
            subtotal.setText(String.valueOf(importe));
            total.setText(String.valueOf(importe));
            productos.setText(" ");
            for (ArrayList<Object> r : datos) {
                for (int i = 0; i < r.size(); i++) {
                    importe=importe+importe;
                    productos.append(r.get(i) + "\t");
                }
                productos.append("\n");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println("Error: " + ex);
        }

    }//GEN-LAST:event_btnBuscadorActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        list.add("Id");
//        list.add("Descripcion");
//        list.add("Precio");
//        list.add("Precion Unitario");
//        list.add("Existencias");
//        list.add("Provedor");

    }//GEN-LAST:event_formWindowOpened

    private void cantidadtextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadtextKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadtextKeyPressed
    ArrayList<ArrayList<Object>> datos = new ArrayList<ArrayList<Object>>();
    ArrayList<Object> list = new ArrayList<Object>();

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Presupuesto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Presupuesto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Presupuesto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Presupuesto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Presupuesto1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Folio;
    private javax.swing.JButton Generar;
    private javax.swing.JTextArea Mensaje;
    private javax.swing.JButton btnBuscador;
    private javax.swing.JTextField buscatext;
    private javax.swing.JTextField cantidadtext;
    private javax.swing.JLabel cerrar;
    private javax.swing.JTextField ciutext;
    private javax.swing.JTextField cptext;
    private javax.swing.JTextField deposito;
    private javax.swing.JTextField desc;
    private javax.swing.JTextField dirtext;
    private javax.swing.JRadioButton evento;
    private com.toedter.calendar.JDateChooser fdevolucion;
    private com.toedter.calendar.JDateChooser fentrega;
    private com.toedter.calendar.JDateChooser fevento;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel minimizar;
    private javax.swing.JTextField nomtext1;
    private javax.swing.JTextField nomtext2;
    private javax.swing.JTextField nomtext3;
    private javax.swing.ButtonGroup opciones;
    private javax.swing.JTextArea productos;
    private javax.swing.JButton regresar;
    private javax.swing.JRadioButton renta;
    private javax.swing.JRadioButton servicio;
    private javax.swing.JTextField subtotal;
    private javax.swing.JTextField teltext;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
